consume:
  target:
    entity:
      domain: number
      integration: inventory_manager
      supported_features:
        - light.LightEntityFeature.EFFECT

  fields:
    amount:
      selector:
        number:
    predefined-amount:
      selector:
        select:
          translation_key: "time"
          options:
            - "morning"
            - "noon"
            - "evening"
            - "night"