store:
  target:
    entity:
      domain: number
      integration: inventory_manager
      supported_features:
        - light.LightEntityFeature.EFFECT
  fields:
    amount:
      required: true
      example: 42
      default: 0
      selector:
        number:
consume:
  target:
    entity:
      domain: number
      integration: inventory_manager
      supported_features:
        - light.LightEntityFeature.EFFECT
  fields:
    amount:
      example: 42
      default: 0
      selector:
        number:
    predefined-amount:
      example: "morning"
      selector:
        select:
          translation_key: time
          options:
            - "morning"
            - "noon"
            - "evening"
            - "night"
            - "week"
            - "month"